<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">usePipelineTag</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional debug</value>
    <value>[i] field:0:required sessionId</value>
    <value>[i] field:0:required pageName</value>
    <value>[i] field:0:required threadName</value>
    <value>[i] field:0:required action</value>
    <value>[i] field:0:required name</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhTWFwIHBpcGVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOwkJCQkKSURhdGEgcmVx
dWVzdCA9IHBpcGVsaW5lOwoKYm9vbGVhbiBkZWJ1ZyA9IGdldERlYnVnKCBwaXBlTWFwICk7CQkK
U3RyaW5nIHNlc3Npb25JZCA9IGdldFNlc3Npb25JZCggcGlwZU1hcCApOwpTdHJpbmcgcGFnZU5h
bWUgPSBnZXRQYWdlTmFtZSggcGlwZU1hcCApOwpTdHJpbmcgdGhyZWFkTmFtZSA9IGdldFNlcnZp
Y2VUaHJlYWQoIHBpcGVNYXAgKTsKU3RyaW5nIGFjdGlvbiA9IGdldEFjdGlvbiggcGlwZU1hcCAp
OwpTdHJpbmcgdGFnU3ZjTmFtZSA9IGdldFRhZ1N2Y05hbWUocGlwZU1hcCk7CgpTdHJpbmcgbmFt
ZSA9IHBpcGVNYXAuZ2V0QXNTdHJpbmcoICJuYW1lIiApOyAvLyBDb25zdGFudHMuTkFNRV9QCgpS
ZXBvcnRlciByZXBvcnRlciA9IEpTUE1hbmFnZXIuZ2V0SW5zdGFuY2UoKS5nZXRSZXBvcnRlcihz
ZXNzaW9uSWQsIHRocmVhZE5hbWUpOwkJCmlmICggcmVwb3J0ZXIgPT0gbnVsbCApIHsKCXJlcG9y
dGVyID0gSlNQTWFuYWdlci5nZXRJbnN0YW5jZSgpLmNyZWF0ZVJlcG9ydGVyKHNlc3Npb25JZCwg
dGhyZWFkTmFtZSwgcmVxdWVzdCk7Cn0JCQkKcmVwb3J0ZXIuc2V0V3JpdGVyKCBnZXRXcml0ZXIo
IHBpcGVNYXAgKSApOwoKaWYgKCBkZWJ1ZyApIHsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcu
Zm9ybWF0KCJcblslc106JXMiLCB0YWdTdmNOYW1lLCBuZXcgamF2YS51dGlsLkRhdGUoKSkpOwoJ
Ly9TeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiUmVwb3J0ZXI6ICVzLi4uJXMiLCBy
ZXBvcnRlciwgcmVwb3J0ZXIuZGVidWcoKSkpOwoJU3lzdGVtLmVyci5wcmludGxuKFN0cmluZy5m
b3JtYXQoIlNlc3Npb25JZDogJXMiLCBzZXNzaW9uSWQpKTsKCVN5c3RlbS5lcnIucHJpbnRsbihT
dHJpbmcuZm9ybWF0KCJwYWdlTmFtZTogJXMiLCBwYWdlTmFtZSkpOwoJU3lzdGVtLmVyci5wcmlu
dGxuKFN0cmluZy5mb3JtYXQoInNlcnZpY2VUaHJlYWQ6ICVzIiwgdGhyZWFkTmFtZSkpOwoJU3lz
dGVtLmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoImFjdGlvbjogJXMiLCBhY3Rpb24pKTsKCVN5
c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJWYXJzOiBuYW1lPSVzIiwgbmFtZSApKTsK
CVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJjdXJyZW50VG9rZW46ICVzIiwgSlNQ
TWFuYWdlci5nZXRJbnN0YW5jZSgpLmdldFRlbXBsYXRlVG9rZW4oc2Vzc2lvbklkLCBnZXRUb2tl
bktleSh0YWdTdmNOYW1lLCB0aHJlYWROYW1lKSkpKTsKfQoKaWYgKCAic3RhcnQiLmVxdWFscyhh
Y3Rpb24pKSB7CgkJCQkKCXBpcGVNYXAucHV0KCAid2VibV9waXBlIiwgcmVwb3J0ZXIuZ2V0Q3Vy
cmVudCgpKTsgLy8gQ29uc3RhbnRzLldFQl9QSVBFX1AgCQkKCUpTUE1hbmFnZXIuZ2V0SW5zdGFu
Y2UoKS51cGRhdGVUb2tlbiggc2Vzc2lvbklkLCBnZXRUb2tlbktleSh0YWdTdmNOYW1lLCB0aHJl
YWROYW1lKSwgbnVsbCk7CgkKfSBlbHNlIHsKCQp9CQoK</value>
</Values>
