<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">caseTag</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional debug</value>
    <value>[i] field:0:required sessionId</value>
    <value>[i] field:0:required pageName</value>
    <value>[i] field:0:required threadName</value>
    <value>[i] field:0:required action</value>
    <value>[i] field:0:required value</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhTWFwIHBpcGVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOwkJCQkKSURhdGEgcmVx
dWVzdCA9IHBpcGVsaW5lOwoKYm9vbGVhbiBkZWJ1ZyA9IGdldERlYnVnKCBwaXBlTWFwICk7CQkK
U3RyaW5nIHNlc3Npb25JZCA9IGdldFNlc3Npb25JZCggcGlwZU1hcCApOwpTdHJpbmcgcGFnZU5h
bWUgPSBnZXRQYWdlTmFtZSggcGlwZU1hcCApOwpTdHJpbmcgdGhyZWFkTmFtZSA9IGdldFNlcnZp
Y2VUaHJlYWQoIHBpcGVNYXAgKTsKU3RyaW5nIGFjdGlvbiA9IGdldEFjdGlvbiggcGlwZU1hcCAp
OwpTdHJpbmcgdGFnU3ZjTmFtZSA9IGdldFRhZ1N2Y05hbWUocGlwZU1hcCk7CgpTdHJpbmcgdmFs
dWUgPSBwaXBlTWFwLmdldEFzU3RyaW5nKCAidmFsIiApOyAvLyBDb25zdGFudHMuVkFMVUVfUCAK
UmVwb3J0ZXIgcmVwb3J0ZXIgPSBKU1BNYW5hZ2VyLmdldEluc3RhbmNlKCkuZ2V0UmVwb3J0ZXIo
IHNlc3Npb25JZCwgdGhyZWFkTmFtZSApOwkKCmlmICggcmVwb3J0ZXIgPT0gbnVsbCApIHsKCXRo
cm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJNaXNzaW5nIHJlcG9ydGVyIGluIGNhc2UgdGFnISBO
byBzd2l0Y2ggdGFnIGluIGpzcCBwYWdlPyIpOwp9CQkJCnJlcG9ydGVyLnNldFdyaXRlciggZ2V0
V3JpdGVyKCBwaXBlTWFwICkgKTsKVGVtcGxhdGVUb2tlbiB0b2tlbiA9IEpTUE1hbmFnZXIuZ2V0
SW5zdGFuY2UoKS5nZXRUZW1wbGF0ZVRva2VuKCBzZXNzaW9uSWQsIHRhZ1N2Y05hbWUgKTsKCmlm
ICggZGVidWcgKSB7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiXG5bJXNdOiVz
IiwgdGFnU3ZjTmFtZSwgbmV3IGphdmEudXRpbC5EYXRlKCkpKTsKCS8vU3lzdGVtLmVyci5wcmlu
dGxuKFN0cmluZy5mb3JtYXQoIlJlcG9ydGVyOiAlcy4uLiVzIiwgcmVwb3J0ZXIsIHJlcG9ydGVy
LmRlYnVnKCkpKTsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJTZXNzaW9uSWQ6
ICVzIiwgc2Vzc2lvbklkKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgicGFn
ZU5hbWU6ICVzIiwgcGFnZU5hbWUpKTsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0
KCJzZXJ2aWNlVGhyZWFkOiAlcyIsIHRocmVhZE5hbWUpKTsKCVN5c3RlbS5lcnIucHJpbnRsbihT
dHJpbmcuZm9ybWF0KCJhY3Rpb246ICVzIiwgYWN0aW9uKSk7CglTeXN0ZW0uZXJyLnByaW50bG4o
U3RyaW5nLmZvcm1hdCgiVmFyczogdmFsPSVzIiwgdmFsdWUgKSk7CglTeXN0ZW0uZXJyLnByaW50
bG4oU3RyaW5nLmZvcm1hdCgiY3VycmVudFRva2VuOiAlcyIsIEpTUE1hbmFnZXIuZ2V0SW5zdGFu
Y2UoKS5nZXRUZW1wbGF0ZVRva2VuKHNlc3Npb25JZCwgdGFnU3ZjTmFtZSkpKTsKfQoKCmlmICgg
dG9rZW4gPT0gbnVsbCkgewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIk1pc3Npbmcgc3dp
dGNoIHRva2VuIGZvciBzd2l0Y2ggdGFnISIpOwp9CgppZiAoICEodG9rZW4gaW5zdGFuY2VvZiBT
d2l0Y2hUb2tlbikpIHsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJQYXJlbnQgdGFnIGlz
IG5vdCBhIHN3aXRjaCB0b2tlbiEiKTsKfQoKCmlmICggInN0YXJ0Ii5lcXVhbHMoYWN0aW9uKSkg
ewoJYm9vbGVhbiBtYXRjaGVzID0gKChTd2l0Y2hUb2tlbil0b2tlbikuZ2V0TWF0Y2goIHJlcG9y
dGVyLCB2YWx1ZSk7CglwaXBlTWFwLnB1dCggIm1hdGNoZXMiLCBtYXRjaGVzKTsgLy9Db25zdGFu
dHMuTUFUQ0hFU19QCn0gZWxzZSB7CgkKfQoK</value>
</Values>
