<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">scopeTag</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional debug</value>
    <value>[i] field:0:required sessionId</value>
    <value>[i] field:0:required pageName</value>
    <value>[i] field:0:required threadName</value>
    <value>[i] field:0:required action</value>
    <value>[i] field:0:required recordName</value>
    <value>[i] field:0:required options</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gWzBdIGZpZWxkOjA6cmVxdWlyZWQgdmFsaWQKCklEYXRhTWFwIHBpcGVNYXAgPSBuZXcgSURh
dGFNYXAocGlwZWxpbmUpOwkJCQkKSURhdGEgcmVxdWVzdCA9IHBpcGVsaW5lOwoKYm9vbGVhbiBk
ZWJ1ZyA9IGdldERlYnVnKCBwaXBlTWFwICk7CQkKU3RyaW5nIHNlc3Npb25JZCA9IGdldFNlc3Np
b25JZCggcGlwZU1hcCApOwpTdHJpbmcgcGFnZU5hbWUgPSBnZXRQYWdlTmFtZSggcGlwZU1hcCAp
OwpTdHJpbmcgdGhyZWFkTmFtZSA9IGdldFNlcnZpY2VUaHJlYWQoIHBpcGVNYXAgKTsKU3RyaW5n
IGFjdGlvbiA9IGdldEFjdGlvbiggcGlwZU1hcCApOwpTdHJpbmcgdGFnU3ZjTmFtZSA9IGdldFRh
Z1N2Y05hbWUocGlwZU1hcCk7CgpTdHJpbmcgcmVjb3JkTmFtZSA9IHBpcGVNYXAuZ2V0QXNTdHJp
bmcoICJyZWNvcmROYW1lIiApOyAvLyBDb25zdGFudHMuUkVDT1JEX1AKU3RyaW5nIG9wdGlvbnMg
PSBwaXBlTWFwLmdldEFzU3RyaW5nKCAib3B0aW9ucyIgKTsgLy8gQ29uc3RhbnRzLk9QVElPTlNf
UAoKSlNQU2NvcGVUb2tlbiB0b2tlbiA9IG51bGw7CgpSZXBvcnRlciByZXBvcnRlciA9IEpTUE1h
bmFnZXIuZ2V0SW5zdGFuY2UoKS5nZXRSZXBvcnRlcihzZXNzaW9uSWQsIHRocmVhZE5hbWUpOwpp
ZiAoIHJlcG9ydGVyID09IG51bGwgKSB7CglyZXBvcnRlciA9IEpTUE1hbmFnZXIuZ2V0SW5zdGFu
Y2UoKS5jcmVhdGVSZXBvcnRlcihzZXNzaW9uSWQsIHRocmVhZE5hbWUsIHJlcXVlc3QpOwp9CQkJ
CnJlcG9ydGVyLnNldFdyaXRlciggZ2V0V3JpdGVyKCBwaXBlTWFwICkgKTsKCmlmICggZGVidWcg
KSB7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiXG5bJXNdOiVzIiwgdGFnU3Zj
TmFtZSwgbmV3IGphdmEudXRpbC5EYXRlKCkpKTsKCS8vU3lzdGVtLmVyci5wcmludGxuKFN0cmlu
Zy5mb3JtYXQoIlJlcG9ydGVyOiAlcy4uLiVzIiwgcmVwb3J0ZXIsIHJlcG9ydGVyLmRlYnVnKCkp
KTsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJTZXNzaW9uSWQ6ICVzIiwgc2Vz
c2lvbklkKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgicGFnZU5hbWU6ICVz
IiwgcGFnZU5hbWUpKTsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJzZXJ2aWNl
VGhyZWFkOiAlcyIsIHRocmVhZE5hbWUpKTsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9y
bWF0KCJhY3Rpb246ICVzIiwgYWN0aW9uKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZv
cm1hdCgiVmFyczogcmVjb3JkTmFtZT0lcywgb3B0aW9ucz0lcyIsIHJlY29yZE5hbWUsIG9wdGlv
bnMgKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiY3VycmVudFRva2VuOiAl
cyIsIEpTUE1hbmFnZXIuZ2V0SW5zdGFuY2UoKS5nZXRUZW1wbGF0ZVRva2VuKHNlc3Npb25JZCwg
Z2V0VG9rZW5LZXkodGFnU3ZjTmFtZSx0aHJlYWROYW1lKSkpKTsKfQoKCgppZiAoICJzdGFydCIu
ZXF1YWxzKGFjdGlvbikpIHsKCXRva2VuID0gbmV3IEpTUFNjb3BlVG9rZW4oIHJlY29yZE5hbWUs
IG9wdGlvbnMgKTsKCXRva2VuLmV2YWwocmVwb3J0ZXIpOwoJSlNQTWFuYWdlci5nZXRJbnN0YW5j
ZSgpLnVwZGF0ZVRva2VuKCBzZXNzaW9uSWQsIGdldFRva2VuS2V5KHRhZ1N2Y05hbWUsIHRocmVh
ZE5hbWUpLCB0b2tlbik7CglwaXBlTWFwLnB1dCggInZhbGlkIiwgdG9rZW4uaXNWYWxpZCgpICk7
IC8vIENvbnN0YW50cy5WQUxJRF9QCgp9IGVsc2UgewoJdG9rZW4gPSAoSlNQU2NvcGVUb2tlbilK
U1BNYW5hZ2VyLmdldEluc3RhbmNlKCkuZ2V0VGVtcGxhdGVUb2tlbihzZXNzaW9uSWQsIGdldFRv
a2VuS2V5KHRhZ1N2Y05hbWUsIHRocmVhZE5hbWUpKTsKCXRva2VuLmVuZChyZXBvcnRlcik7Cn0K
Cg==</value>
</Values>
