<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">invokeTag</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional debug</value>
    <value>[i] field:0:required sessionId</value>
    <value>[i] field:0:required pageName</value>
    <value>[i] field:0:required threadName</value>
    <value>[i] field:0:required username</value>
    <value>[i] field:0:required fullSvcName</value>
    <value>[i] field:0:required newPipe</value>
    <value>[i] field:0:required writer</value>
    <value>[i] field:0:required action</value>
    <value>[o] field:0:required error</value>
    <value>[o] field:0:required errorMessage</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">ICAJCgpJRGF0YU1hcCBwaXBlTWFwID0gbmV3IElEYXRhTWFwKHBpcGVsaW5lKTsJCQkJCklEYXRh
IHJlcXVlc3QgPSBwaXBlbGluZTsKCmJvb2xlYW4gZGVidWcgPSBnZXREZWJ1ZyggcGlwZU1hcCAp
OwkJClN0cmluZyBzZXNzaW9uSWQgPSBnZXRTZXNzaW9uSWQoIHBpcGVNYXAgKTsKU3RyaW5nIHBh
Z2VOYW1lID0gZ2V0UGFnZU5hbWUoIHBpcGVNYXAgKTsKU3RyaW5nIHRocmVhZE5hbWUgPSBnZXRT
ZXJ2aWNlVGhyZWFkKCBwaXBlTWFwICk7ClN0cmluZyBhY3Rpb24gPSBnZXRBY3Rpb24oIHBpcGVN
YXAgKTsKU3RyaW5nIHRhZ1N2Y05hbWUgPSBnZXRUYWdTdmNOYW1lKHBpcGVNYXApOwkJCgpTdHJp
bmcgdXNlcm5hbWUgPSBwaXBlTWFwLmdldEFzU3RyaW5nKCJ1c2VybmFtZSIpOyAvL0NvbnN0YW50
cy5LRVlfUElQRUxJTkVfVVNFUk5BTUUKU3RyaW5nIGZ1bGxTdmNOYW1lID0gcGlwZU1hcC5nZXRB
c1N0cmluZygiZnVsbFN2Y05hbWUiKTsvL0NvbnN0YW50cy5LRVlfUElQRUxJTkVfU0VSVklDRU5B
TUUKSURhdGEgbmV3UGlwZSA9IHBpcGVNYXAuZ2V0QXNJRGF0YSgibmV3UGlwZSIpOwppZiAobmV3
UGlwZSA9PSBudWxsKSB7CglJRGF0YU1hcCBtID0gbmV3IElEYXRhTWFwKCk7CgluZXdQaXBlID0g
bS5nZXRJRGF0YSgpOwp9CmlmICggZnVsbFN2Y05hbWUgPT0gbnVsbCB8fCBmdWxsU3ZjTmFtZS5s
ZW5ndGgoKSA9PSAwICkgewogICAgU2VydmVyLmxvZ0Vycm9yKChTdHJpbmcpbnVsbCwgInNlcnZp
Y2VJbnRlcmZhY2UvTmFtZSBpbnB1dHMgYXJlIHJlcXVpcmVkIik7CiAgICB0aHJvdyBuZXcgU2Vy
dmljZUV4Y2VwdGlvbigic2VydmljZUludGVyZmFjZS9OYW1lIGlucHV0cyBhcmUgcmVxdWlyZWQg
Zm9yIGludm9rZVRhZ1NlcnZpY2UiKTsKfQoKUmVwb3J0ZXIgcmVwb3J0ZXIgPSBKU1BNYW5hZ2Vy
LmdldEluc3RhbmNlKCkuZ2V0UmVwb3J0ZXIoc2Vzc2lvbklkLCB0aHJlYWROYW1lKTsKaWYgKCBy
ZXBvcnRlciA9PSBudWxsICkgewoJcmVwb3J0ZXIgPSBKU1BNYW5hZ2VyLmdldEluc3RhbmNlKCku
Y3JlYXRlUmVwb3J0ZXIoc2Vzc2lvbklkLCB0aHJlYWROYW1lLCByZXF1ZXN0KTsKfQkJCQpyZXBv
cnRlci5zZXRXcml0ZXIoIGdldFdyaXRlciggcGlwZU1hcCApICk7CgppZiAoIGRlYnVnICkgewoJ
U3lzdGVtLmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoIlxuWyVzXTolcyIsIHRhZ1N2Y05hbWUs
IG5ldyBqYXZhLnV0aWwuRGF0ZSgpKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1h
dCgiZnVsbFN2Y05hbWU6ICVzIiwgZnVsbFN2Y05hbWUpKTsKCS8vU3lzdGVtLmVyci5wcmludGxu
KFN0cmluZy5mb3JtYXQoIlJlcG9ydGVyOiAlcy4uLiVzIiwgcmVwb3J0ZXIsIHJlcG9ydGVyLmRl
YnVnKCkpKTsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJTZXNzaW9uSWQ6ICVz
Iiwgc2Vzc2lvbklkKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgicGFnZU5h
bWU6ICVzIiwgcGFnZU5hbWUpKTsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJz
ZXJ2aWNlVGhyZWFkOiAlcyIsIHRocmVhZE5hbWUpKTsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJp
bmcuZm9ybWF0KCJhY3Rpb246ICVzIiwgYWN0aW9uKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3Ry
aW5nLmZvcm1hdCgiVmFyczogdXNlcm5hbWU9JXMsIGZ1bGxTdmNOYW1lPSVzLCBuZXdQaXBlPSVz
IiwgdXNlcm5hbWUsIGZ1bGxTdmNOYW1lLCBuZXdQaXBlICkpOwoJU3lzdGVtLmVyci5wcmludGxu
KFN0cmluZy5mb3JtYXQoImN1cnJlbnRUb2tlbjogJXMiLCBKU1BNYW5hZ2VyLmdldEluc3RhbmNl
KCkuZ2V0VGVtcGxhdGVUb2tlbihzZXNzaW9uSWQsIGdldFRva2VuS2V5KHRhZ1N2Y05hbWUsdGhy
ZWFkTmFtZSkpKSk7Cn0KICAgCgogCkpTUEludm9rZVRva2VuIHRva2VuID0gbnVsbDsKCmlmICgg
InN0YXJ0Ii5lcXVhbHMoYWN0aW9uKSkgewoKCXRva2VuID0gbmV3IEpTUEludm9rZVRva2VuKE5T
TmFtZS5jcmVhdGUoZnVsbFN2Y05hbWUpKTsKCQoJLy8gc2V0IHVwIHRoZSBJbnZva2VTdGF0ZQoJ
SW52b2tlU3RhdGUgc3RhdGUgPSBpbml0aWFsaXplSW52b2tlU3RhdGUoKTsKCWlmICggSW52b2tl
U3RhdGUuZ2V0Q3VycmVudFVzZXIoKSA9PSBudWxsKSB7CgkKCQlVc2VyIHVzZXIgPSBVc2VyTWFu
YWdlci5nZXRVc2VyKHVzZXJuYW1lKTsKCQlJbnZva2VTdGF0ZS5zZXRDdXJyZW50VXNlciggdXNl
ciApOwoJfQoJCgoJLy8gZXZhbHVhdGUgdGhlIHRva2VuCgkvLyB0aGUgc2VydmljZSBpbnZvY2F0
aW9uIGhhcHBlbnMgaGVyZQoJdG9rZW4uZXZhbChyZXBvcnRlcik7CglKU1BNYW5hZ2VyLmdldElu
c3RhbmNlKCkudXBkYXRlVG9rZW4oIHNlc3Npb25JZCwgZ2V0VG9rZW5LZXkodGFnU3ZjTmFtZSx0
aHJlYWROYW1lKSwgdG9rZW4pOwoJCQkJCQkKCWlmICggdG9rZW4uaXNFcnJvcigpKSB7CgkJcGlw
ZU1hcC5wdXQoIiRlcnJvciIsIHRydWUpOyAvLyBDb25zdGFudHMuSVNfRVJST1JfUAoJCXBpcGVN
YXAucHV0KCIkZXJyb3JNZXNzYWdlIiwgdG9rZW4uZ2V0RXJyb3JNZXNzYWdlKCkpOyAvLyBDb25z
dGFudHMuRVJST1JfTUVTU0FHRV9QCgl9CgkgICAgCn0gZWxzZSBpZiAoICJlbmQiLmVxdWFscyhh
Y3Rpb24pKSB7Cgl0b2tlbiA9IChKU1BJbnZva2VUb2tlbilKU1BNYW5hZ2VyLmdldEluc3RhbmNl
KCkuZ2V0VGVtcGxhdGVUb2tlbihzZXNzaW9uSWQsIGdldFRva2VuS2V5KHRhZ1N2Y05hbWUsdGhy
ZWFkTmFtZSkpOwoJdG9rZW4uZW5kKHJlcG9ydGVyKTsKCglpZiAoIHRva2VuLmlzRXJyb3IoKSkg
ewoJCXBpcGVNYXAucHV0KCIkZXJyb3IiLCB0cnVlKTsgLy8gQ29uc3RhbnRzLklTX0VSUk9SX1AK
CQlwaXBlTWFwLnB1dCgiJGVycm9yTWVzc2FnZSIsIHRva2VuLmdldEVycm9yTWVzc2FnZSgpKTsg
Ly8gQ29uc3RhbnRzLkVSUk9SX01FU1NBR0VfUAoJfQoKfQkJCgkJCQo=</value>
</Values>
