<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">valueTag</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional debug</value>
    <value>[i] field:0:required sessionId</value>
    <value>[i] field:0:required pageName</value>
    <value>[i] field:0:required threadName</value>
    <value>[i] field:0:required action</value>
    <value>[i] field:0:required name</value>
    <value>[i] field:0:required index</value>
    <value>[i] field:0:required nullval</value>
    <value>[i] field:0:required emptyval</value>
    <value>[i] field:0:required encode</value>
    <value>[i] field:0:required decode</value>
    <value>[i] field:0:required decshift</value>
    <value>[i] field:0:required decshow</value>
    <value>[i] field:0:required var</value>
    <value>[i] field:0:required isStruct</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhTWFwIHBpcGVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOwkJCQkKSURhdGEgcmVx
dWVzdCA9IHBpcGVsaW5lOwoKYm9vbGVhbiBkZWJ1ZyA9IGdldERlYnVnKCBwaXBlTWFwICk7CQkK
U3RyaW5nIHNlc3Npb25JZCA9IGdldFNlc3Npb25JZCggcGlwZU1hcCApOwpTdHJpbmcgcGFnZU5h
bWUgPSBnZXRQYWdlTmFtZSggcGlwZU1hcCApOwpTdHJpbmcgdGhyZWFkTmFtZSA9IGdldFNlcnZp
Y2VUaHJlYWQoIHBpcGVNYXAgKTsKU3RyaW5nIGFjdGlvbiA9IGdldEFjdGlvbiggcGlwZU1hcCAp
OwpTdHJpbmcgdGFnU3ZjTmFtZSA9IGdldFRhZ1N2Y05hbWUocGlwZU1hcCk7CgpTdHJpbmcgbmFt
ZSA9IHBpcGVNYXAuZ2V0QXNTdHJpbmcoICJuYW1lIiApOyAvLyBDb25zdGFudHMuTkFNRV9QCmlu
dCBpbmRleCA9IHBpcGVNYXAuZ2V0QXNJbnRlZ2VyKCAiaW5kZXgiICk7IC8vIENvbnN0YW50cy5J
TkRFWF9QClN0cmluZyBudWxsdmFsID0gcGlwZU1hcC5nZXRBc1N0cmluZyggIm51bGx2YWwiICk7
IC8vIENvbnN0YW50cy5OVUxMX1ZBTFVFX1AKU3RyaW5nIGVtcHR5dmFsID0gcGlwZU1hcC5nZXRB
c1N0cmluZyggImVtcHR5dmFsIiApOyAvLyBDb25zdGFudHMuRU1QVFlfVkFMVUVfUAppbnQgd21F
bmNvZGUgPSBnZXRFbmNvZGUoIHBpcGVNYXAuZ2V0QXNTdHJpbmcoICJlbmNvZGUiKSApOyAvLyBD
b25zdGFudHMuV01fRU5DT0RFX1AKaW50IHdtRGVjb2RlID0gZ2V0RGVjb2RlKCBwaXBlTWFwLmdl
dEFzU3RyaW5nKCAiZGVjb2RlIikgKTsgLy8gQ29uc3RhbnRzLldNX0RFQ09ERV9QCmludCBkZWNz
aGlmdCA9IHBpcGVNYXAuZ2V0QXNJbnRlZ2VyKCAiZGVjc2hpZnQiICk7IC8vIENvbnN0YW50cy5E
RUNfU0hJRlRfUAppbnQgZGVjc2hvdyA9IHBpcGVNYXAuZ2V0QXNJbnRlZ2VyKCAiZGVjc2hvdyIg
KTsgLy8gQ29uc3RhbnRzLkRFQ19TSE9XX1AKU3RyaW5nIGxvb3BWYXIgPSBwaXBlTWFwLmdldEFz
U3RyaW5nKCAidmFyIiApOyAvLyBDb25zdGFudHMuVkFSSUFCTEVfUCAKYm9vbGVhbiBpc0xvb3BT
dHJ1Y3QgPSBwaXBlTWFwLmdldEFzQm9vbGVhbiggImlzU3RydWN0IiApOyAvLyBDb25zdGFudHMu
U1RSVUNUX1AJCQoKVmFsdWVUb2tlbiB0b2tlbiA9IG51bGw7CgpSZXBvcnRlciByZXBvcnRlciA9
IEpTUE1hbmFnZXIuZ2V0SW5zdGFuY2UoKS5nZXRSZXBvcnRlciggc2Vzc2lvbklkLCB0aHJlYWRO
YW1lKTsKaWYgKCByZXBvcnRlciA9PSBudWxsICkgewoJcmVwb3J0ZXIgPSBKU1BNYW5hZ2VyLmdl
dEluc3RhbmNlKCkuY3JlYXRlUmVwb3J0ZXIoc2Vzc2lvbklkLCB0aHJlYWROYW1lLCByZXF1ZXN0
KTsKfQkJCQpyZXBvcnRlci5zZXRXcml0ZXIoIGdldFdyaXRlciggcGlwZU1hcCApICk7CgppZiAo
IGRlYnVnICkgewoJU3lzdGVtLmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoIlxuWyVzXTolcyIs
IHRhZ1N2Y05hbWUsIG5ldyBqYXZhLnV0aWwuRGF0ZSgpKSk7CgkvL1N5c3RlbS5lcnIucHJpbnRs
bihTdHJpbmcuZm9ybWF0KCJSZXBvcnRlcjogJXMuLi4lcyIsIHJlcG9ydGVyLCByZXBvcnRlci5k
ZWJ1ZygpKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiU2Vzc2lvbklkOiAl
cyIsIHNlc3Npb25JZCkpOwoJU3lzdGVtLmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoInBhZ2VO
YW1lOiAlcyIsIHBhZ2VOYW1lKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgi
c2VydmljZVRocmVhZDogJXMiLCB0aHJlYWROYW1lKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3Ry
aW5nLmZvcm1hdCgiYWN0aW9uOiAlcyIsIGFjdGlvbikpOwoJU3lzdGVtLmVyci5wcmludGxuKFN0
cmluZy5mb3JtYXQoCgkJCSJWYXJzOiBuYW1lPSVzLCBpbmRleD0lcywgbnVsbHZhbD0lcywgZW1w
dHl2YWw9JXMsIGVuY29kZT0lcywgZGVjb2RlPSVzLCBkZWNzaGlmdD0lcywgZGVjc2hvdz0lcywg
bG9vcFZhcj0lcywgaXNMb29wU3RydWN0PSVzIiwgCgkJCSBuYW1lLCBpbmRleCwgbnVsbHZhbCwg
ZW1wdHl2YWwsIHdtRW5jb2RlLCB3bURlY29kZSwgZGVjc2hpZnQsIGRlY3Nob3csIGxvb3BWYXIs
IGlzTG9vcFN0cnVjdCApKTsKCVN5c3RlbS5lcnIucHJpbnRsbihTdHJpbmcuZm9ybWF0KCJjdXJy
ZW50VG9rZW46ICVzIiwgSlNQTWFuYWdlci5nZXRJbnN0YW5jZSgpLmdldFRlbXBsYXRlVG9rZW4o
c2Vzc2lvbklkLCBnZXRUb2tlbktleSh0YWdTdmNOYW1lLHRocmVhZE5hbWUpKSkpOwp9CgppZiAo
ICJzdGFydCIuZXF1YWxzKGFjdGlvbiApKSB7CgkKfSBlbHNlIGlmICggImVuZCIuZXF1YWxzKGFj
dGlvbikpIHsKCXRva2VuID0gbmV3IFZhbHVlVG9rZW4obmFtZSwgaW5kZXgsIG51bGx2YWwsIGVt
cHR5dmFsLCB3bUVuY29kZSwgZGVjc2hpZnQsIGRlY3Nob3cpOwkKCQoJCglpZiAoIGxvb3BWYXIg
IT0gbnVsbCApIHsKCQkvLyBmaWd1cmUgb3V0IHdoZXJlIHRvIGdldCBlbmNvZGluZyBmcm9tIAoJ
CS8vIHVzYXdjbyBOb3RlOiB0aGUgZXhpc3RpbmcgV21Ub21jYXQgY29kZSBhbHNvIHBhc3NlZCBu
dWxsLiAKCQkvLyBJdCBsb29rZWQgbGlrZSB0aGlzIHBhcmFtZXRlciBpcyBubyBsb25nZXIgdXNl
ZCBpbiB0aGlzIG1ldGhvZCBjYWxsLCBUT0RPIC0gZG91YmxlLWNoZWNrCgkJdG9rZW4uZXZhbExv
b3BWYWx1ZShyZXBvcnRlciwgbnVsbCwgbG9vcFZhciwgaXNMb29wU3RydWN0KTsKCQkKCX0gZWxz
ZSB7CgkJdG9rZW4uZXZhbChyZXBvcnRlcik7Cgl9CQkJCglKU1BNYW5hZ2VyLmdldEluc3RhbmNl
KCkudXBkYXRlVG9rZW4oIHNlc3Npb25JZCwgZ2V0VG9rZW5LZXkodGFnU3ZjTmFtZSx0aHJlYWRO
YW1lKSwgdG9rZW4pOwp9Cg==</value>
</Values>
