<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ifVarTag</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional debug</value>
    <value>[i] field:0:required sessionId</value>
    <value>[i] field:0:required pageName</value>
    <value>[i] field:0:required threadName</value>
    <value>[i] field:0:required action</value>
    <value>[i] field:0:required var</value>
    <value>[i] field:0:required equals</value>
    <value>[i] field:0:required vequals</value>
    <value>[i] field:0:required isNull</value>
    <value>[i] field:0:required notEmpty</value>
    <value>[i] field:0:required matches</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhTWFwIHBpcGVNYXAgPSBuZXcgSURhdGFNYXAocGlwZWxpbmUpOwkJCQkKSURhdGEgcmVx
dWVzdCA9IHBpcGVsaW5lOwoKYm9vbGVhbiBkZWJ1ZyA9IGdldERlYnVnKCBwaXBlTWFwICk7CQkK
U3RyaW5nIHNlc3Npb25JZCA9IGdldFNlc3Npb25JZCggcGlwZU1hcCApOwpTdHJpbmcgcGFnZU5h
bWUgPSBnZXRQYWdlTmFtZSggcGlwZU1hcCApOwpTdHJpbmcgdGhyZWFkTmFtZSA9IGdldFNlcnZp
Y2VUaHJlYWQoIHBpcGVNYXAgKTsKU3RyaW5nIGFjdGlvbiA9IGdldEFjdGlvbiggcGlwZU1hcCAp
OwpTdHJpbmcgdGFnU3ZjTmFtZSA9IGdldFRhZ1N2Y05hbWUocGlwZU1hcCk7CgpTdHJpbmcgdmFy
aWFibGUgPSBwaXBlTWFwLmdldEFzU3RyaW5nKCAidmFyIiApOyAvLyBDb25zdGFudHMuVkFSSUFC
TEVfUCAKU3RyaW5nIGVxdWFscyA9IHBpcGVNYXAuZ2V0QXNTdHJpbmcoICJlcXVhbHMiICk7IC8v
IENvbnN0YW50cy5FUVVBTFNfUCAKU3RyaW5nIHZlcXVhbHMgPSBwaXBlTWFwLmdldEFzU3RyaW5n
KCAidmVxdWFscyIgKTsgLy8gQ29uc3RhbnRzLlZFUVVBTFNfUCAKU3RyaW5nIG1hdGNoZXMgPSBw
aXBlTWFwLmdldEFzU3RyaW5nKCAibWF0Y2hlcyIgKTsgLy8gQ29uc3RhbnRzLk1BVENIRVNfUCAK
Ym9vbGVhbiBpc051bGwgPSBwaXBlTWFwLmdldEFzQm9vbGVhbiggImlzTnVsbCIgKTsgLy8gQ29u
c3RhbnRzLklTX05VTExfUApib29sZWFuIG5vdEVtcHR5ID0gcGlwZU1hcC5nZXRBc0Jvb2xlYW4o
ICJub3RFbXB0eSIgKTsgLy8gQ29uc3RhbnRzLk5PVF9FTVBUWV9QIAoKSlNQSWZWYXJUb2tlbiB0
b2tlbiA9IG51bGw7ClJlcG9ydGVyIHJlcG9ydGVyID0gSlNQTWFuYWdlci5nZXRJbnN0YW5jZSgp
LmdldFJlcG9ydGVyKHNlc3Npb25JZCwgdGhyZWFkTmFtZSApOwppZiAoIHJlcG9ydGVyID09IG51
bGwgKSB7CglyZXBvcnRlciA9IEpTUE1hbmFnZXIuZ2V0SW5zdGFuY2UoKS5jcmVhdGVSZXBvcnRl
cihzZXNzaW9uSWQsIHRocmVhZE5hbWUsIHJlcXVlc3QpOwp9CQkJCnJlcG9ydGVyLnNldFdyaXRl
ciggZ2V0V3JpdGVyKCBwaXBlTWFwICkgKTsKCmlmICggZGVidWcgKSB7CglTeXN0ZW0uZXJyLnBy
aW50bG4oU3RyaW5nLmZvcm1hdCgiXG5bJXNdOiVzIiwgdGFnU3ZjTmFtZSwgbmV3IGphdmEudXRp
bC5EYXRlKCkpKTsKCS8vU3lzdGVtLmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoIlJlcG9ydGVy
OiAlcy4uLi4lcyIsIHJlcG9ydGVyLCByZXBvcnRlci5kZWJ1ZygpKSk7CglTeXN0ZW0uZXJyLnBy
aW50bG4oU3RyaW5nLmZvcm1hdCgiU2Vzc2lvbklkOiAlcyIsIHNlc3Npb25JZCkpOwoJU3lzdGVt
LmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoInBhZ2VOYW1lOiAlcyIsIHBhZ2VOYW1lKSk7CglT
eXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgic2VydmljZVRocmVhZDogJXMiLCB0aHJl
YWROYW1lKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiYWN0aW9uOiAlcyIs
IGFjdGlvbikpOwoJU3lzdGVtLmVyci5wcmludGxuKFN0cmluZy5mb3JtYXQoIlZhcnM6IHZhcj0l
cywgZXF1YWxzPSVzLCB2ZXF1YWxzPSVzLCBtYXRjaGVzPSVzLCBpc051bGw9JXMsIG5vdEVtcHR5
PSVzIiwgCgkJCXZhcmlhYmxlLCBlcXVhbHMsIHZlcXVhbHMsIG1hdGNoZXMsIGlzTnVsbCwgbm90
RW1wdHkgKSk7CglTeXN0ZW0uZXJyLnByaW50bG4oU3RyaW5nLmZvcm1hdCgiY3VycmVudFRva2Vu
OiAlcyIsIEpTUE1hbmFnZXIuZ2V0SW5zdGFuY2UoKS5nZXRUZW1wbGF0ZVRva2VuKCBzZXNzaW9u
SWQsIGdldFRva2VuS2V5KHRhZ1N2Y05hbWUsdGhyZWFkTmFtZSkgKSkpOwp9CgoKaWYgKCAic3Rh
cnQiLmVxdWFscyhhY3Rpb24pKSB7CgkKCXRva2VuID0gbmV3IEpTUElmVmFyVG9rZW4oIHZhcmlh
YmxlLCBpc051bGwsIG5vdEVtcHR5LCBlcXVhbHMsIHZlcXVhbHMsIG1hdGNoZXMgKTsJCQkKCXRv
a2VuLmV2YWwocmVwb3J0ZXIpOwoJSlNQTWFuYWdlci5nZXRJbnN0YW5jZSgpLnVwZGF0ZVRva2Vu
KCBzZXNzaW9uSWQsIGdldFRva2VuS2V5KHRhZ1N2Y05hbWUsdGhyZWFkTmFtZSksIHRva2VuKTsK
CQoJcGlwZU1hcC5wdXQoICJyZXN1bHQiLCB0b2tlbi5nZXRSZXN1bHQoKSApOyAvLyBDb25zdGFu
dHMuUkVTVUxUX1AKCgkKfSBlbHNlIHsKCQoJdG9rZW4gPSAoSlNQSWZWYXJUb2tlbilKU1BNYW5h
Z2VyLmdldEluc3RhbmNlKCkuZ2V0VGVtcGxhdGVUb2tlbihzZXNzaW9uSWQsIGdldFRva2VuS2V5
KHRhZ1N2Y05hbWUsdGhyZWFkTmFtZSkpOwoJdG9rZW4uZW5kKCByZXBvcnRlciApOwoKCQp9Cg==
</value>
</Values>
